site_name: VKPyBot Documentation
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.footer
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

repo_url: https://github.com/Vlatterran/vkpybot
plugins:
  - search:
      lang:
        - en
        - ru
  - i18n:
      docs_structure: folder
      default_language: ru
      languages:
        en: English
        ru: Русский
  - mkdocstrings:
      handlers:

        python:
          options:
            show_source: false
#  - gen-files:
#      scripts:
#        - docs/ru/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vlatterran/vkpybot