[tool.poetry]
name = "vk"
version = "0.1.0"
description = ""
authors = ["vlad"]
packages = [
    { include = "core" },
    { include = "core/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "~3.7.4.post0"
docstring-parser = "0.12"
requests = "~2.26.0"
setuptools = "~57.0.0"
pydantic= "~1.9.0"
PyYAML = "^6.0"
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
debugbot = "examples.DebugBot:main"
mybot = "examples.MyBot:main"