name: Pytest tests

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11", "3.10"]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: | 
          poetry install --with dev
      - name: Test with pytest ${{ matrix.runs-on }}
        run:  poetry run pytest

